### PR TITLE
Add bors config

### PR DESCRIPTION
**Pull request by nicholastmosher**

### CODE REVIEW

**Comment by nicholastmosher** [comment]
bors ping

**Comment by nicholastmosher** [comment]
@sehz I just tried requesting access for Bors on this repo, can you check if you got the request? After you accept the request you should be able to use `bors ping` here and it will respond so you know it's set up correctly.

**Comment by sehz** [comment]
bors ping

**Comment by nicholastmosher** [comment]
Ok cool. As the last step, @sehz can you add a branch-protection rule on `master` that requires the `bors` status check to pass? That will block the green merge button and force us to use Bors like we do in the other repos. Also if this PR looks good to you, feel free to `bors r+` it.

**Review by sehz — APPROVED** [review]
LGTM

**Pull request merged**
